### ISSUE TITLE
better encryption for master private key

### ISSUE THREAD

**Issue by gits7r** [DonnchaC/onionbalance#13]
A key function of OnionBalance is to protect the master private key. In case the master server hosting onionbalance is compromised, the private key and therefor the address of the hidden service remains safe. 

To do:
- ensure the private key is encrypted with a good cipher, like AES128 or AES256

To think about:
- what is the smartest way onionbalance can use to access the encrypted private key and sign the master descriptor? Is it possible it won't leave any trace of the decryption key in RAM, so no matter if the server is compromised while running, the hidden service address will still remain safe?

**Comment by DonnchaC** [comment]
OnionBalance uses the pycrpyto library which unfortunately has only implemented support for DES and 3DES encryption of RSA private keys [1]. I could implement this myself in OnionBalance but that may not be much more useful.

Its tricky to manage private key material in a language like Python which performs its own memory management. The SecureDrop people have done quite a lot of work on this, but I think the conclusion is that you can definitively clean keys from RAM in a running Python process.

I think smartcard and HSM support is the best way to try and defend hidden service key material from adversaries who compromise the OnionBalance machine.

I can reopen this ticket if anyone really desires stronger encryption than 3DES for the private key.
 
[1] https://www.dlitz.net/software/pycrypto/api/current/Crypto.PublicKey.RSA-module.html#importKey
