### ISSUE TITLE
Create .deb package for OnionBalance

### ISSUE THREAD

**Issue by DonnchaC** [DonnchaC/onionbalance#15]
Packaging as a .deb would provide a more secure method for users to install OnionBalance and it's dependencies.

The packaging proccess for standard Python packages looks relatively straightforward: https://wiki.debian.org/Python/Packaging

**Comment by Jesse-V** [comment]
Making a .deb file is pretty straightforward. You will need a debian folder with control files in it, feel free to copy the one in any of my OnioNS repositories. I also have a script that builds manpages and builds the package. If you want to upload to Launchpad for remote building, I can help with that too. It's hard to figure out at first, but I've already fought the battle and would be happy to assist.

**Comment by DonnchaC** [comment]
The ``schedule`` package is not currenty

**Comment by Jesse-V** [comment]
Here is my script for creating .deb files: https://github.com/Jesse-V/OnioNS-common/blob/master/.travis.yml I built them for the Travis CI continuous integration system, but they can also be run manually for the same effect.They are for C++, but I imagine that they could be adapted to fit your system.

**Comment by bencevans** [comment]
https://github.com/jordansissel/fpm looks like a good option for packaging Python modules more automagically for multiple platforms.

**Comment by FedericoCeratto** [comment]
The Debian packaging is at https://anonscm.debian.org/cgit/pkg-privacy/packages/onionbalance.git

**Comment by DonnchaC** [comment]
The package is now in Debian Sid https://packages.debian.org/source/sid/onionbalance
