### ISSUE TITLE
Consider publishing multiple descriptors with different sets of IP's

### ISSUE THREAD

**Issue by DonnchaC** [DonnchaC/onionbalance#16]
Currently OnionBalance will included descriptors from up to 10 backend instances in the service descriptor. The 10 IP hard-limit could effectively be increased by publishing a different set of IP's in each descriptor. This could be useful when a service operator would like to run multiple Tor instances per server to more fully utilize a multi-core system.

It's not clear yet if anyone actually needs to type of behaviour, but it is something which can be considered in future.

**Comment by gits7r** [comment]
Not a priority from my point of view. OnionBalance can scale very well with the 10 IPs allowed in a single one master descriptor. So far we are not sure if the introduction points could be the bottleneck - I was able to have ~1700 simultaneous open rend circuits on a failback instance which had 2 introduction points in the master descriptor.

I think this will confuse users as well as complicate the code - we should be considering it when/if we decide introduction points are / can be a possible bottleneck.

**Comment by gits7r** [comment]
P.S. better and easier for 'scaling like crazy' an user could run OnionBalance in cascade:

HS A [onionbalance with 5 failback instances B, C, D, E]
 -> failback instance B [onionbalance with 5 failback instances]
-> failback instance C [onionbalance with 5 failback instances]
-> . ======= // =======.
Would grant a total of 25 failback instances of the same master HS.

This would just require for us to build a good tutorial page and properly educate the users - it won't complicate onionbalance's code. Let's keep it simple, strong and stable and think out of the box at upper levels. (just my opinion).

**Comment by gits7r** [comment]
I think something worth looking into is choosing different IPs for the failback instances all the time and rotate them in the master descriptor. 

Let's assume we have HS A with 5 failback instances. Each failback instance will have, let's assume 6 IPs each, but OnionBalance will only choose 2 from each and publish 10 IPs (2 per failback instance) in the master descriptor.

When republishing the master descriptor, if the IPs of the failback instances didn't change, always select other 2 IPs (from the total of 6) related to each failback instance as compared to previous master descriptor. Never republish a master descriptor with the very same IPs per failback instance (not even for just one failback instance) - this will load balance even better, giving a fair use of as many IPs as possible from each failback instance. Will this be complicated to implement? 

Excuse me if this is not entirely accurate, just sent an email with exact question to better understand the algorithm used - looking forward to hear about it.

**Comment by gits7r** [comment]
Need to close this in favor of #18 - it is better explained there and if implemented it will also partially address the initial reason of this ticket.
