### ISSUE TITLE
Write blog post describing the OnionBalance HS stress tests.

### ISSUE THREAD

**Issue by DonnchaC** [DonnchaC/onionbalance#17]
@gits7r has done some great work stress testing an OnionBalance backed hidden service and gathering useful performance data.

For the longer term, it would be great to summarize the results into a blog post for blog.torproject.org. I've created an initial pad to collaborate at https://etherpad.mozilla.org/HxfW6mUuFX

**Comment by asn-d6** [comment]
The etherpad is dead, the dream is dead. Let's reopen if we get interested in blog post again.
