### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by alecmuffett** [DonnchaC/onionbalance#63]
REFRESH_INTERVAL
How often to check for updated backend hidden service descriptors. This value can be increased if your backend instance are under heavy loaded causing them to rotate introduction points quickly. (default: 600 seconds).

...shouldn't that say `can be decreased`?

**Comment by DonnchaC** [comment]
Yes, it definitely should say `can be decreased`. Thanks for spotting this. I've fixed this in 404ac51.
