### ISSUE TITLE
Write tutorial which uses OnionBalance to load balance between multiple web servers

### ISSUE THREAD

**Issue by DonnchaC** [DonnchaC/onionbalance#8]
The current documentation is quite abstract and could to a better job of getting a new users up and running.

The tutorial should outline the full process for:
-  Setting up the web servers 
- Configure the back end Tor instances
- Creating an OnionBalance config file
- Running the OnionBalance management server with a supervisor process

**Comment by pyhedgehog** [comment]
Especially interesting topic is dynamically adding/removing backend servers. I want to create docker image that anyone (in our organization) can run to provide bandwidth and redundancy.
